[project]
name = "agent-orchestra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain-community>=0.3.18",
    "mlx-lm>=0.21.4",
    "smolagents>=1.9.2",
    "sqlalchemy>=2.0.38",
]
